spring:
  profiles: development

server:
  port: 8080

---
spring:
  profiles: default

  resources:
    cachePeriod: 31556926

server:
  port: 80

---
spring:
  profiles: compression
spring: 
  profiles: 
    include: default

